version: '3'
services:
  ####################################################################################################
  # Creating container MySQL
  ####################################################################################################
  mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes:
        - ./image/mysql/data/:/var/lib/mysql
    env_file:
      - Docker/mysql/.mysql-env

  ####################################################################################################
  # The Redis Server
  ####################################################################################################
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    expose:
        - 6379
    volumes:
        - ./image/redis/data:/data
    env_file:
      - Docker/redis/.redis-env

  ####################################################################################################
  # The Application
  ####################################################################################################
  app:
    build:
      context: ./
      dockerfile: Docker/app/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - Docker/app/.app-env
    links:
      - mysql
      - redis

  ####################################################################################################
  # The Web Server
  ####################################################################################################
  nginx:
    build:
      context: ./
      dockerfile: Docker/nginx/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    env_file:
      - Docker/nginx/.nginx-env
    ports:
      - "80:80"
    depends_on:
      - app