version: '3'
services:
  ####################################################################################################
  # Creating container MySQL
  ####################################################################################################
  mysql:
    container_name: ${MYSQL_NAME}_${MYSQL_TAG}
    image: "${MYSQL_NAME}:${MYSQL_TAG}"
    build:
      context: ./
      dockerfile: ./docker-compose/mysql/Dockerfile
      args:
        - TAG=${MYSQL_TAG}
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes:
        - ./docker-compose/image/mysql/data/:/var/lib/mysql

  ####################################################################################################
  # The Redis Server
  ####################################################################################################
  redis:
    container_name: ${REDIS_NAME}_${REDIS_TAG}
    image: "${REDIS_NAME}:${REDIS_TAG}"
    build:
      context: ./
      dockerfile: ./docker-compose/redis/Dockerfile
      args:
        - TAG=${REDIS_TAG}
    ports:
        - "6379:6379"
    expose:
        - 6379
    volumes:
        - ./docker-compose/image/redis/data:/data

  # Use it with command: docker-compose run redis-cli
  redis-cli:
    container_name: ${NAME}_redis-cli
    image: "${REDIS_NAME}:${REDIS_TAG}"
    links:
      - redis
    command: redis-cli -h redis

  ####################################################################################################
  # The Application
  ####################################################################################################
  workspace:
    container_name: ${WORKSPACE_NAME}_${WORKSPACE_TAG}
    image: "${WORKSPACE_NAME}:${WORKSPACE_TAG}"
    build:
      context: ./
      dockerfile: ./docker-compose/workspace/Dockerfile
      args:
        - TAG=${WORKSPACE_TAG}
        - COMPOSER_UPDATE=${COMPOSER_UPDATE}
    working_dir: /var/www
    volumes:
      - ./application:/var/www
    links:
      - mysql
      - redis

  ####################################################################################################
  # The Web Server
  ####################################################################################################
  nginx:
    container_name: ${NGINX_NAME}_${NGINX_TAG}
    image: "${NGINX_NAME}:${NGINX_TAG}"
    build:
      context: ./
      dockerfile: ./docker-compose/nginx/Dockerfile
      args:
        - TAG=${NGINX_TAG}
    working_dir: /var/www
    volumes:
      - ./docker-compose/image/nginx/data/:/var/www
    ports:
      - "80:80"
    depends_on:
      - workspace
